swagger:
  enable: true
  title: AA Life
  description: AA Life API Document
  version: 1.0
  url:
  author:
    name: Brother Lu
    email: 1285823170@qq.com
    url:

threadPool:
  name: aalife-async-thread
  keepAlive: 5
  allowCoreTimeOut: true
  size:
    max: 20
    core: 3
    capacity: 200

file:
  baseDir: E:/

server:
  port: 443
  ssl:
    key-store: classpath:1529882054683.pfx
    key-store-password: 1529882054683
    keyAlisa: tomcat
    keyStoreType: PKCS12
  session:
    timeout: 3600
  contextPath: /

spring:
  application: aalife
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/life_v2?zeroDateTimeBehavior=convertToNull&verifyServerCertificate=false&useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: aalife
    password: mysql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
  mvc:
    static-path-pattern: /resources/img/**
  resources:
    static-locations: classpath:/static/img


  mail:
    host: smtp.aliyun.com
    port: 465
    username: brotherlu@aliyun.com
    password: xct19960321@
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
      mail:
        smtp:
          ssl:
            enable: true
    from: IT服务中心<brotherlu@aliyun.com>